### ISSUE TITLE
Create initial data for app

### ISSUE THREAD

**Issue by tisana** [dst-hackathon/fpv-api-spring#6]
Building
Floor
Desk
Employee

Create data in csv format. Put it under src/main/resources/config/liquibase/

**Comment by mekeerati** [comment]
- Plan : DST 2016-11
  - Building : RSU Tower
    - Floor : 17
      - Desk : R1
      - Desk : R2
      - Desk : R3
    - Floor : 18
      - Desk : R1
      - Desk : R2
      - Desk : R3
  - Building : Broadway Building

**Comment by mekeerati** [comment]
Change h2 to file mode and commit to repository to make database structure clean

**Comment by sataphat** [comment]
May need to dump into MySQL instead

**Comment by mekeerati** [comment]
h2 is using as development database. however, i will point prod mode to mysql db instead.
